[ACL4SSR]
name=ACL4SSR
url=https://github.com/LittleYe233/ACL4SSR
branch=main
match=Clash/*.list|Clash/Ruleset/**

[ACL4SSR_config]
name=ACL4SSR
url=https://github.com/LittleYe233/ACL4SSR
branch=main
match=Clash/config/**
dest=base/config/
keep_tree=false